export default {
    AUTH_ERROR: 'AUTH_ERROR',
    LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
    LOG_OUT: 'LOG_OUT',
    UPDATE_COURSES: 'UPDATE_COURSES',
    UPDATE_CLASSROOM: 'UPDATE_CLASSROOM',
    UPDATE_USER: 'UPDATE_USER',
    UPDATE_TEMPLATES: 'UPDATE_TEMPLATES',
    UPDATE_LESSON: 'UPDATE_LESSON',
    LOADING: 'LOADING',
    LOADING_SUCCESS: 'LOADING_SUCCESS',
    GET_TEST_RESULTS: 'GET_TEST_RESULTS',
    GET_QUESTIONS: 'GET_QUESTIONS',
    UPDATE_INSTRUCTORS: 'UPDATE_INSTRUCTORS',
    BROADCAST_MESSAGE: 'BROADCAST_MESSAGE',
    END_BROADCAST: 'END_BROADCAST',
};

